@IF "%_echo%"=="" (ECHO OFF) else (ECHO ON)

CALL :RESOLVEPATH "%~dp0\."
SET VFS_SCRIPTSDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_SCRIPTSDIR%\.."
SET VFS_SRCDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_SRCDIR%\.."
SET VFS_ENLISTMENTDIR=%_PARSED_PATH_%

SET VFS_OUTDIR=%VFS_ENLISTMENTDIR%\out
SET VFS_PACKAGESDIR=%VFS_OUTDIR%\packages
SET VFS_PUBLISHDIR=%VFS_OUTDIR%\publish

REM Clean up
SET _PARSED_PATH_=

GOTO :EOF

:RESOLVEPATH
SET "_PARSED_PATH_=%~f1"
GOTO :EOF
